version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8888:8080"
    depends_on:
      - mongo
      #  condition: service_healthy
    environment:
      - DOCKER_CONTAINER=true
    networks:
      - blog-network

  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - blog-network

volumes:
  mongo-data:

networks:
  blog-network:
    driver: bridge