basePath: /
definitions:
  pkg.Comment:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      post_id:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  pkg.Post:
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  pkg.Response:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  pkg.User:
    properties:
      id:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple blog API
  title: Blog API
  version: "1.0"
paths:
  /api/posts:
    get:
      description: Get all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Post'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Create a new post
      parameters:
      - description: Post object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Create a new post
      tags:
      - posts
  /api/posts/{id}:
    delete:
      description: Get a post by ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Post'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get a post by ID
      tags:
      - posts
    get:
      description: Get a post by ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Post'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get a post by ID
      tags:
      - posts
    patch:
      consumes:
      - application/json
      description: Update a post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Post object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Update a post
      tags:
      - posts
  /api/posts/{id}/comments:
    get:
      description: Get comments for a post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Comment'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get comments for a post
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: Add a comment to a post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Comment object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Add a comment to a post
      tags:
      - comments
  /api/posts/comments:
    get:
      description: Get all comments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Comment'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all comments
      tags:
      - comments
  /api/posts/comments/{commentID}:
    delete:
      description: Delete a comment
      parameters:
      - description: Comment ID
        in: path
        name: commentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Delete a comment
      tags:
      - comments
    patch:
      consumes:
      - application/json
      description: Update a comment
      parameters:
      - description: Comment ID
        in: path
        name: commentID
        required: true
        type: string
      - description: Comment object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Update a comment
      tags:
      - comments
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Login a user
      tags:
      - users
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/pkg.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Register a new user
      tags:
      - users
  /auth/users:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
